# Reference: ESPnet2 conformer recipe; reduced adim and layers
encoder: conformer
encoder_conf:
  output_size: 256 # NEW: 256 (vs 512 in full) for VRAM constraint
  attention_heads: 4
  linear_units: 2048
  num_blocks: 12
  dropout_rate: 0.1
  positional_dropout_rate: 0.1
  attention_dropout_rate: 0.1
  input_layer: conv2d
  normalize_before: true
  macaron_style: true
  rel_pos_type: latest
  pos_enc_layer_type: rel_pos
  selfattention_layer_type: rel_selfattn
  activation_type: swish
  use_cnn_module: true
  cnn_module_kernel: 31

decoder: transformer
decoder_conf:
  attention_heads: 4
  linear_units: 2048
  num_blocks: 6
  dropout_rate: 0.1
  positional_dropout_rate: 0.1
  self_attention_dropout_rate: 0.1
  src_attention_dropout_rate: 0.1
  layer_drop_rate: 0.0 # librispeech 100

model_conf:
  ctc_weight: 0.3 # per bab3.tex eq:persamaan-ctc α = 0.3
  lsm_weight: 0.1 # librispeech 100
  length_normalized_loss: false # librispeech 100

seed: 777

optim: adam
optim_conf:
  lr: 0.002 # librispeech 100; pref: 0.001
scheduler: warmuplr
scheduler_conf:
  warmup_steps: 15000 # librispeech 100; pref: 25000

specaug: specaug
specaug_conf:
  apply_time_warp: true
  time_warp_window: 5
  time_warp_mode: bicubic # librispeech 100; pref: none
  apply_freq_mask: true
  freq_mask_width_range:
    - 0
    - 27
  num_freq_mask: 2
  apply_time_mask: true
  time_mask_width_ratio_range:
    - 0.
    - 0.05
  num_time_mask: 5 # librispeech 100; pref: 2

max_epoch: 5

patience: 10
val_scheduler_criterion:
  - valid
  - acc
best_model_criterion:
  - - valid
    - acc
    - max

batch_type: numel
batch_bins: 300000 # 11 GB def: 350000 fallback 1: 300000; 2: 250000; 6 GB: 200000
# batch_bins: 350000 # 11 GB fallback 1: 300000; 2: 250000; 6 GB: 200000
accum_grad: 2

grad_clip: 5

num_workers: 2
