batch_type: numel
batch_bins: 1000000
accum_grad: 48
max_epoch: 10
num_workers: 2
seed: 777

patience: 2
best_model_criterion:
  - - valid
    - acc # voxtlm: loss
    - max # voxtlm: min
keep_nbest_models: 10

lm: transformer_opt
lm_conf:
  opt_name: "facebook/opt-350m"

optim: adam
optim_conf:
  lr: 0.0005
  weight_decay: 0.00001
scheduler: warmuplr
scheduler_conf:
  warmup_steps: 2000
