batch_type: length
batch_bins: 10000
accum_grad: 20
# num_iters_per_epoch: 25000
max_epoch: 20 # from voxtlm 250; test on 50; remove iter/epoch
num_workers: 2
# grad_clip: 1.0
seed: 777

patience: none
best_model_criterion:
  - - valid
    - acc # voxtlm: loss
    - max # voxtlm: min
keep_nbest_models: 10

lm: transformer_opt
lm_conf:
  opt_name: "facebook/opt-350m"

model_conf:
  lsm_weight: 0.1
  length_normalized_loss: true

optim: adam
optim_conf:
  lr: 0.0005 # voxtlm: 0.0003; test: 0.0005 lower train data
  weight_decay: 0.00001 # voxtlm: 1e-06; test: 1e-5
scheduler: warmuplr
scheduler_conf:
  warmup_steps: 2000 # voxtlm: 2500; test: 2500 small train data
